class GameEvent:
    NO_RESPAWN_BLOCK_AVAILABLE = 0
    BEGIN_RAINING = 1
    END_RAINING = 2
    CHANGE_GAME_MODE = 3
    WIN_GAME = 4
    DEMO_EVENT = 5
    ARROW_HIT_PLAYER = 6
    RAIN_LEVEL_CHANGE = 7
    THUNDER_LEVEL_CHANGE = 8
    PLAY_PUFFERFISH_STING_SOUND = 9
    PLAY_ELDER_GUARDIAN_MOB_APPEARANCE = 10
    ENABLE_RESPAWN_SCREEN = 11
    LIMITED_CRAFTING = 12
    START_WAITING_FOR_LEVEL_CHUNKS = 13
